export type Trip = {
  id: string;
  slug: string;
  name: string;
  location: string;
  difficulty: string;
  description: string | null;
  price: string;
  date_start: string;
  date_end: string;
  leader_id: string;
  quota_max: number;
  image_url: string;
  member_count: number;
  featured?: boolean;
  status?: string | null;
  price_amount?: number | null;
  requires_approval?: boolean;
  application_prompt?: string | null;
  activity_category?: string | null;
};
